## Algoritmos genéticos
### Individuos

In [6]:
import random as rnd

def inicializarIndividuo(individuo):
    total = 1.0
    cantidadGenes = len(individuo)
    
    for counter in range(0, cantidadGenes):
        if(counter == cantidadGenes - 1):
            individuo[counter] = total
        else:
            randomValue = rnd.uniform(0, total)
            individuo[counter] = randomValue
            total -= randomValue
    return individuo

In [7]:
import numpy as np

def generarPoblacion(cantidadDeIndividuos, cantidadDeGenes):
    poblacion = np.zeros((cantidadDeIndividuos, cantidadDeGenes))
    
    for counter in range(0, cantidadDeIndividuos):
        poblacion[counter] = inicializarIndividuo(poblacion[counter])
    return poblacion

In [8]:
poblacion = generarPoblacion(cantidadDeIndividuos=5, cantidadDeGenes=3)
print(poblacion)

[[0.55615895 0.27390707 0.16993398]
 [0.7605732  0.16254537 0.07688142]
 [0.86592821 0.03036824 0.10370355]
 [0.83290355 0.14987963 0.01721682]
 [0.5248863  0.19180664 0.28330707]]


In [9]:
def cruzarIndividuos(individuo1, individuo2):
    crossPoint = rnd.randint(1, len(individuo1) - 2)
    hijo1 = np.append(individuo1[0:crossPoint], individuo2[crossPoint:len(individuo1)])
    hijo2 = np.append(individuo2[0:crossPoint], individuo1[crossPoint:len(individuo1)])
    hijo1 = ajustarIndividuo(hijo1)
    hijo2 = ajustarIndividuo(hijo2)
    return np.array([hijo1, hijo2])

In [10]:
def ajustarIndividuo(individuo):
    total = np.sum(individuo)
    individuo = individuo / total
    return individuo

In [11]:
def cruzarPoblacion(poblacion, probabilidadDeCruza):
    nuevaPoblacion = None
    for counter in range(len(poblacion)):
        probabilidad = rnd.random()
        if(probabilidad < probabilidadDeCruza):
            pareja = rnd.randint(0, len(poblacion) - 2)
            while pareja == counter:
                pareja = rnd.randint(0, len(poblacion) - 2)
                
            nuevosIndividuos = cruzarIndividuos(poblacion[counter], poblacion[pareja])
            
            if nuevaPoblacion is None:
                nuevaPoblacion = nuevosIndividuos
            else:
                nuevaPoblacion = np.concatenate((nuevaPoblacion, nuevosIndividuos))
                
        if not nuevaPoblacion is None:
            poblacion = np.concatenate((poblacion, nuevaPoblacion))
        return poblacion

In [12]:
poblacionBasal = generarPoblacion(8, 6)
print(poblacionBasal)

[[3.31486092e-01 3.52172471e-01 1.55127431e-01 5.28680437e-03
  4.91385823e-02 1.06788620e-01]
 [8.17422152e-01 8.58416639e-02 5.02051009e-02 3.35712650e-02
  1.32041448e-03 1.16394042e-02]
 [5.46900048e-01 3.28749515e-01 9.94651646e-02 1.40323549e-02
  5.37642866e-04 1.03152751e-02]
 [4.18988620e-01 4.41898851e-02 4.40807669e-01 4.85535502e-02
  7.26183881e-04 4.67340913e-02]
 [1.53767352e-01 7.82475554e-01 6.05573553e-02 3.01063982e-03
  1.44133046e-04 4.49654309e-05]
 [5.81705225e-01 3.31567193e-01 5.36671956e-02 2.45769739e-02
  2.83039581e-03 5.65301719e-03]
 [7.88397639e-01 1.55647342e-01 4.30482692e-02 9.48727626e-03
  2.14798906e-03 1.27148370e-03]
 [5.98666748e-01 3.54200192e-01 3.46400084e-02 3.77261737e-03
  2.85776590e-03 5.86266846e-03]]


In [14]:
poblacionNueva = cruzarPoblacion(poblacionBasal, 0.385)
print(poblacionNueva)

[[3.31486092e-01 3.52172471e-01 1.55127431e-01 5.28680437e-03
  4.91385823e-02 1.06788620e-01]
 [8.17422152e-01 8.58416639e-02 5.02051009e-02 3.35712650e-02
  1.32041448e-03 1.16394042e-02]
 [5.46900048e-01 3.28749515e-01 9.94651646e-02 1.40323549e-02
  5.37642866e-04 1.03152751e-02]
 [4.18988620e-01 4.41898851e-02 4.40807669e-01 4.85535502e-02
  7.26183881e-04 4.67340913e-02]
 [1.53767352e-01 7.82475554e-01 6.05573553e-02 3.01063982e-03
  1.44133046e-04 4.49654309e-05]
 [5.81705225e-01 3.31567193e-01 5.36671956e-02 2.45769739e-02
  2.83039581e-03 5.65301719e-03]
 [7.88397639e-01 1.55647342e-01 4.30482692e-02 9.48727626e-03
  2.14798906e-03 1.27148370e-03]
 [5.98666748e-01 3.54200192e-01 3.46400084e-02 3.77261737e-03
  2.85776590e-03 5.86266846e-03]]


### Mutaciones

In [21]:
def mutacion(individuo):
    mutationPoint = rnd.randint(1, len(individuo) - 2)
    mutationValue = rnd.uniform(0.1, 0.3)
    individuoMutante = np.array(individuo, copy=True)
    individuoMutante[mutationPoint] += mutationValue
    individuoMutante = ajustarIndividuo(individuoMutante)
    return np.array([individuoMutante])

In [22]:
def mutarPoblacion(poblacion, probabilidadDeMutacion):
    nuevaPoblacion = None
    for counter in range(len(poblacion)):
        probabilidad = rnd.random()
        if(probabilidad < probabilidadDeMutacion):
            nuevoMutante = mutacion(poblacion[counter])
            if nuevaPoblacion is None:
                nuevaPoblacion = nuevoMutante
            else:
                nuevaPoblacion = np.concatenate((nuevaPoblacion, nuevoMutante))
    if not nuevaPoblacion is None:
        poblacion = np.concatenate((poblacion, nuevaPoblacion))
    return poblacion

In [23]:
poblacionMutante = mutarPoblacion(poblacionNueva, 0.128)
print(poblacionMutante)

[[3.31486092e-01 3.52172471e-01 1.55127431e-01 5.28680437e-03
  4.91385823e-02 1.06788620e-01]
 [8.17422152e-01 8.58416639e-02 5.02051009e-02 3.35712650e-02
  1.32041448e-03 1.16394042e-02]
 [5.46900048e-01 3.28749515e-01 9.94651646e-02 1.40323549e-02
  5.37642866e-04 1.03152751e-02]
 [4.18988620e-01 4.41898851e-02 4.40807669e-01 4.85535502e-02
  7.26183881e-04 4.67340913e-02]
 [1.53767352e-01 7.82475554e-01 6.05573553e-02 3.01063982e-03
  1.44133046e-04 4.49654309e-05]
 [5.81705225e-01 3.31567193e-01 5.36671956e-02 2.45769739e-02
  2.83039581e-03 5.65301719e-03]
 [7.88397639e-01 1.55647342e-01 4.30482692e-02 9.48727626e-03
  2.14798906e-03 1.27148370e-03]
 [5.98666748e-01 3.54200192e-01 3.46400084e-02 3.77261737e-03
  2.85776590e-03 5.86266846e-03]
 [3.59072290e-01 3.78706306e-02 5.20773450e-01 4.16102816e-02
  6.22337927e-04 4.00510095e-02]]


### Supervivencia

In [30]:
def evaluacion(poblacion, ganancias, probabilidadDeExito):
    puntaje = np.zeros(poblacion.shape[0])
    
    puntajeDeGanancia = np.dot(poblacion, ganancias)
    puntajeDeExito = np.dot(poblacion, probabilidadDeExito)
    puntaje = puntajeDeGanancia + puntajeDeExito
    
    ordenDeMayorAMenor = np.argsort(-puntaje)
    poblacionOrdenada = poblacion[ordenDeMayorAMenor]
    mejorPuntaje = (np.sort(-puntaje)[0]) * -1
    return poblacionOrdenada, mejorPuntaje

In [31]:
def eliminarIndividuosPorPorcentaje(poblacion, porcentajeAMantener):
    cantidad = poblacion.shape[0]
    cantidadAMantener = int(porcentajeAMantener * cantidad)
    return poblacion[:cantidadAMantener]

In [32]:
def eliminarIndividuosPorCantidad(poblacion, cantidadAMantener):
    return poblacion[:cantidadAMantener]

In [35]:
poblacionBasal = generarPoblacion(10, 4)
totalGeneracion = 0
ganacias = [0.1, 0.1, 0.9, 0.1]
probabilidadesDeExito = [0.1, 0.1, 0.9, 0.1]

for generacion in range(0, totalGeneracion):
    poblacion = cruzarPoblacion(poblacionBasal, 0.385)
    poblacio = mutarPoblacion(poblacionCruzada, 0.128)
    poblacion, mejorPuntaje = evaluacion(poblacion, ganancias, probabilidadDeExito)
    poblacion = eliminarIndividuosPorCantidad(poblacion, 5)
    print("Mejor puntaje de la generación: " + str(generacion) + "\n"+ "Mejor puntaje: " + str(mejorPuntaje))
    generacion +=1
    
print("Solución: " + str(poblacion[0]))

Solución: [0.55615895 0.27390707 0.16993398]
